# -*- coding: utf-8 -*-
"""
Created on Tue Jun 27 14:32:42 2023

@author: Nicolas
"""

from plotProduction import *
from generateBoundExample import *
print('Loaded modules')
    
#%%

print('Loading data')


def readBenchmarkResults():
    firstIndx = 0
    data = np.loadtxt('TurnerBenchmark/turner_benchmark_results.dat')
    case1 = data[0:129,:]
    firstIndx = firstIndx + 129
    case2 = data[firstIndx:firstIndx+257,:]
    firstIndx = firstIndx + 257
    case3 = data[firstIndx:firstIndx+513, :]
    firstIndx = firstIndx+513
    case4 = data[firstIndx:firstIndx+513]
    return case1,case2,case3,case4

def readBenchmarkResultsRefined():
    data = np.loadtxt('TurnerBenchmark/turner_benchmark_refined_results.dat')
    indx = np.where(data[:,0] == 0)[0]
    case1 = data[indx[0]:indx[1], :]
    case2 = data[indx[1]:indx[2], :]
    case3 = data[indx[2]:indx[3], :]
    case4 = data[indx[3]:,:]
    return case1, case2, case3, case4



case1, case2, case3, case4 = readBenchmarkResults()
case1_refined, case2_refined, case3_refined, case4_refined = readBenchmarkResultsRefined()

Exp_RFBenchmark_case1 = dataSetExplicit('Y:/ImplicitPic1D/ExplicitData/Exp_RFBenchmark_case1/')
ECExp_RFBenchmark_case1 = dataSetExplicit('Y:/ImplicitPic1D/ExplicitData/ECPIC_RF_Benchmark_case1/')
NGP_RF_Benchmark_case1 = dataSet('Y:/ImplicitPic1D/ImplicitData/NGP_RF_Benchmark_case1/')
CIC_RF_Benchmark_case1 = dataSet('Y:/ImplicitPic1D/ImplicitData/CIC_RF_Benchmark_case1/')
Exp_RFBenchmark_case1_20xParticles = dataSetExplicit('Y:/ImplicitPic1D/ExplicitData/Exp_RFBenchmark_case1_20xParticles/')
Exp_RFBenchmark_case1_halfTime_doubleCells_doubleParticles = dataSetExplicit('Y:/ImplicitPic1D/ExplicitData/Exp_RFBenchmark_case1_halfTime_doubleCells_doubleParticles/')
NGP_RF_Benchmark_case1_10xParticles = dataSet('Y:/ImplicitPic1D/ImplicitData/NGP_RF_Benchmark_case1_10xParticles/')
CIC_RF_Benchmark_case1_10xParticles = dataSet('Y:/ImplicitPic1D/ImplicitData/CIC_RF_Benchmark_case1_10xParticles/')


Exp_RFBenchmark_Denis = dataSetExplicit('Y:/ImplicitPic1D/ExplicitData/Exp_RFBenchmark_Denis/')
Exp_RFBenchmark_Denis_doubleTime = dataSetExplicit('Y:/ImplicitPic1D/ExplicitData/Exp_RFBenchmark_Denis_doubleTime/')
Exp_RFBenchmark_Denis_doubleTime_halfPart = dataSetExplicit('Y:/ImplicitPic1D/ExplicitData/Exp_RFBenchmark_Denis_doubleTime_halfPart/')
Exp_RFBenchmark_Denis_doubleTime_halfPart_PCG = dataSetExplicit('Y:/ImplicitPic1D/ExplicitData/Exp_RFBenchmark_Denis_doubleTime_halfPart_PCG/')
Exp_RFBenchmark_Denis_doubleTime_quartPart = dataSetExplicit('Y:/ImplicitPic1D/ExplicitData/Exp_RFBenchmark_Denis_doubleTime_quartPart/')
Exp_RFBenchmark_Denis_tripleTime = dataSetExplicit('Y:/ImplicitPic1D/ExplicitData/Exp_RFBenchmark_Denis_tripleTime/')
Exp_RFBenchmark_Denis_moreCells = dataSetExplicit('Y:/ImplicitPic1D/ExplicitData/Exp_RFBenchmark_Denis_moreCells/')
Exp_RFBenchmark_Denis_moreCells_doublePart = dataSetExplicit('Y:/ImplicitPic1D/ExplicitData/Exp_RFBenchmark_Denis_moreCells_doublePart/')
Exp_RFBenchmark_Denis_moreCells_quadPart = dataSetExplicit('Y:/ImplicitPic1D/ExplicitData/Exp_RFBenchmark_Denis_moreCells_quadPart/')
Exp_RFBenchmark_Denis_moreCells_40xPart = dataSetExplicit('Y:/ImplicitPic1D/ExplicitData/Exp_RFBenchmark_Denis_moreCells_40xPart/')
Exp_RFBenchmark_Denis_3000Cells_20xPart_thirdsTime = dataSetExplicit('Y:/ImplicitPic1D/ExplicitData/Exp_RFBenchmark_Denis_3000Cells_20xPart_thirdsTime/')

Exp_RFBenchmark_Denis_lowerDen_doubleTime_1024Cells_64PPC = dataSetExplicit('Y:/ImplicitPic1D/ExplicitData/Exp_RFBenchmark_Denis_lowerDen_doubleTime_1024Cells_64PPC/')
Exp_RFBenchmark_Denis_lowerDen_doubleTime_1024Cells_128PPC = dataSetExplicit('Y:/ImplicitPic1D/ExplicitData/Exp_RFBenchmark_Denis_lowerDen_doubleTime_1024Cells_128PPC/')
Exp_RFBenchmark_Denis_lowerDen_1024Cells_128PPC = dataSetExplicit('Y:/ImplicitPic1D/ExplicitData/Exp_RFBenchmark_Denis_lowerDen_1024Cells_128PPC/')
Exp_RFBenchmark_Denis_moreCells_lowerDen_halfPart = dataSetExplicit('Y:/ImplicitPic1D/ExplicitData/Exp_RFBenchmark_Denis_moreCells_lowerDen_halfPart/')
Exp_RFBenchmark_Denis_moreCells_lowerDen = dataSetExplicit('Y:/ImplicitPic1D/ExplicitData/Exp_RFBenchmark_Denis_moreCells_lowerDen/')
Exp_RFBenchmark_Denis_moreCells_lowerDen_doublePart = dataSetExplicit('Y:/ImplicitPic1D/ExplicitData/Exp_RFBenchmark_Denis_moreCells_lowerDen_doublePart/')
Exp_RFBenchmark_Denis_moreCells_lowerDen_quadPart = dataSetExplicit('Y:/ImplicitPic1D/ExplicitData/Exp_RFBenchmark_Denis_moreCells_lowerDen_quadPart/')
Exp_RFBenchmark_Denis_moreCells_lowerDen_10xPart = dataSetExplicit('Y:/ImplicitPic1D/ExplicitData/Exp_RFBenchmark_Denis_moreCells_lowerDen_10xPart/')
Exp_RFBenchmark_Denis_moreCells_lowerDen_10xPart_halfTime = dataSetExplicit('Y:/ImplicitPic1D/ExplicitData/Exp_RFBenchmark_Denis_moreCells_lowerDen_10xPart_halfTime/')
Exp_RFBenchmark_Denis_moreCells_lowerDen_20xPart = dataSetExplicit('Y:/ImplicitPic1D/ExplicitData/Exp_RFBenchmark_Denis_moreCells_lowerDen_20xPart/')
Exp_RFBenchmark_Denis_moreCells_lowerDen_20xPart_3000cells_thirdsTime = dataSetExplicit('Y:/ImplicitPic1D/ExplicitData/Exp_RFBenchmark_Denis_moreCells_lowerDen_20xPart_3000cells_thirdsTime/')

ECExp_RFBenchmark_Denis_lowerDen_524PPC_128cells_noSmoothing_sinCenter = dataSetExplicit('Y:/ImplicitPic1D/ExplicitData/ECExp_RFBenchmark_Denis_lowerDen_524PPC_128cells_noSmoothing_sinCenter/')

# ----------------------- NGP ---------------------------------

NGP_RFBenchmark_Denis_262PPC_128cells_noSmoothing = dataSet('Y:/ImplicitPic1D/ImplicitData/NGP_RFBenchmark_Denis_262PPC_128cells_noSmoothing/')
NGP_RFBenchmark_Denis_524PPC_128cells_noSmoothing = dataSet('Y:/ImplicitPic1D/ImplicitData/NGP_RFBenchmark_Denis_524PPC_128cells_noSmoothing/')


NGP_RFBenchmark_Denis_131PPC_128cells_noSmoothing_sinCenter = dataSet('Y:/ImplicitPic1D/ImplicitData/NGP_RFBenchmark_Denis_131PPC_128cells_noSmoothing_sinCenter/')
NGP_RFBenchmark_Denis_131PPC_128cells_noSmoothing_sinCenter_Curv = dataSet('Y:/ImplicitPic1D/ImplicitData/NGP_RFBenchmark_Denis_131PPC_128cells_noSmoothing_sinCenter_Curv/')
NGP_RFBenchmark_Denis_262PPC_128cells_noSmoothing_sinCenter = dataSet('Y:/ImplicitPic1D/ImplicitData/NGP_RFBenchmark_Denis_262PPC_128cells_noSmoothing_sinCenter/')
NGP_RFBenchmark_Denis_524PPC_128cells_noSmoothing_sinCenter = dataSet('Y:/ImplicitPic1D/ImplicitData/NGP_RFBenchmark_Denis_524PPC_128cells_noSmoothing_sinCenter/')
NGP_RFBenchmark_Denis_1048PPC_128cells_noSmoothing_sinCenter = dataSet('Y:/ImplicitPic1D/ImplicitData/NGP_RFBenchmark_Denis_1048PPC_128cells_noSmoothing_sinCenter/')
NGP_RFBenchmark_Denis_2096PPC_128cells_noSmoothing_sinCenter = dataSet('Y:/ImplicitPic1D/ImplicitData/NGP_RFBenchmark_Denis_2096PPC_128cells_noSmoothing_sinCenter/')

NGP_RFBenchmark_Denis_131PPC_128cells_Smoothing_sinCenter = dataSet('Y:/ImplicitPic1D/ImplicitData/NGP_RFBenchmark_Denis_131PPC_128cells_Smoothing_sinCenter/')
NGP_RFBenchmark_Denis_262PPC_128cells_Smoothing_sinCenter = dataSet('Y:/ImplicitPic1D/ImplicitData/NGP_RFBenchmark_Denis_262PPC_128cells_Smoothing_sinCenter/')
NGP_RFBenchmark_Denis_524PPC_128cells_Smoothing_sinCenter = dataSet('Y:/ImplicitPic1D/ImplicitData/NGP_RFBenchmark_Denis_524PPC_128cells_Smoothing_sinCenter/')
NGP_RFBenchmark_Denis_1048PPC_128cells_Smoothing_sinCenter = dataSet('Y:/ImplicitPic1D/ImplicitData/NGP_RFBenchmark_Denis_1048PPC_128cells_Smoothing_sinCenter/')


NGP_RFBenchmark_Denis_131PPC_256cells_noSmoothing = dataSet('Y:/ImplicitPic1D/ImplicitData/NGP_RFBenchmark_Denis_131PPC_256cells_noSmoothing/')
NGP_RFBenchmark_Denis_262PPC_256cells_noSmoothing = dataSet('Y:/ImplicitPic1D/ImplicitData/NGP_RFBenchmark_Denis_262PPC_256cells_noSmoothing/')
NGP_RFBenchmark_Denis_524PPC_256cells_noSmoothing = dataSet('Y:/ImplicitPic1D/ImplicitData/NGP_RFBenchmark_Denis_524PPC_256cells_noSmoothing/')
NGP_RFBenchmark_Denis_1048PPC_256cells_noSmoothing = dataSet('Y:/ImplicitPic1D/ImplicitData/NGP_RFBenchmark_Denis_1048PPC_256cells_noSmoothing/')
NGP_RFBenchmark_Denis_1048PPC_256cells_noSmoothing_PCG = dataSet('Y:/ImplicitPic1D/ImplicitData/NGP_RFBenchmark_Denis_1048PPC_256cells_noSmoothing_PCG/')
NGP_RFBenchmark_Denis_2096PPC_256cells_noSmoothing = dataSet('Y:/ImplicitPic1D/ImplicitData/NGP_RFBenchmark_Denis_2096PPC_256cells_noSmoothing/')
NGP_RFBenchmark_Denis_4192PPC_256cells_noSmoothing = dataSet('Y:/ImplicitPic1D/ImplicitData/NGP_RFBenchmark_Denis_4192PPC_256cells_noSmoothing/')
NGP_RFBenchmark_Denis_2096PPC_256cells_noSmoothing_OGTime = dataSet('Y:/ImplicitPic1D/ImplicitData/NGP_RFBenchmark_Denis_2096PPC_256cells_noSmoothing_OGTime/')

NGP_RFBenchmark_Denis_1048PPC_1024cells_noSmoothing = dataSet('Y:/ImplicitPic1D/ImplicitData/NGP_RFBenchmark_Denis_1048PPC_1024cells_noSmoothing/')
NGP_RFBenchmark_Denis_1048PPC_1024cells_noSmoothing_OGTime = dataSet('Y:/ImplicitPic1D/ImplicitData/NGP_RFBenchmark_Denis_1048PPC_1024cells_noSmoothing_OGTime/')

NGP_RFBenchmark_Denis_512PPC_2000cells_noSmoothing = dataSet('Y:/ImplicitPic1D/ImplicitData/NGP_RFBenchmark_Denis_512PPC_2000cells_noSmoothing/')
NGP_RFBenchmark_Denis_1024PPC_2000cells_noSmoothing = dataSet('Y:/ImplicitPic1D/ImplicitData/NGP_RFBenchmark_Denis_1024PPC_2000cells_noSmoothing/')
NGP_RFBenchmark_Denis_1024PPC_2500cells_neg11Sec_noSmoothing = dataSet('Y:/ImplicitPic1D/ImplicitData/NGP_RFBenchmark_Denis_1024PPC_2500cells_neg11Sec_noSmoothing/')
NGP_RFBenchmark_Denis_2000PPC_2500cells_neg11Sec_noSmoothing = dataSet('Y:/ImplicitPic1D/ImplicitData/NGP_RFBenchmark_Denis_2000PPC_2500cells_neg11Sec_noSmoothing/')


NGP_RFBenchmark_Denis_262PPC_128cells_noSmoothing_normTime = dataSet('Y:/ImplicitPic1D/ImplicitData/NGP_RFBenchmark_Denis_262PPC_128cells_noSmoothing_normTime/')

NGP_RFBenchmark_Denis_lowerDen_131PPC_128cells_noSmoothing = dataSet('Y:/ImplicitPic1D/ImplicitData/NGP_RFBenchmark_Denis_lowerDen_131PPC_128cells_noSmoothing/')
NGP_RFBenchmark_Denis_lowerDen_262PPC_128cells_noSmoothing = dataSet('Y:/ImplicitPic1D/ImplicitData/NGP_RFBenchmark_Denis_lowerDen_262PPC_128cells_noSmoothing/')

NGP_RFBenchmark_Denis_lowerDen_131PPC_64cells_noSmoothing_sinCenter = dataSet('Y:/ImplicitPic1D/ImplicitData/NGP_RFBenchmark_Denis_lowerDen_131PPC_64cells_noSmoothing_sinCenter/')

NGP_RFBenchmark_Denis_lowerDen_524PPC_128cells_noSmoothing_denisMap = dataSet('Y:/ImplicitPic1D/ImplicitData/NGP_RFBenchmark_Denis_lowerDen_524PPC_128cells_noSmoothing_denisMap/')
NGP_RFBenchmark_Denis_lowerDen_524PPC_128cells_noSmoothing_denisMap_try = dataSet('Y:/ImplicitPic1D/ImplicitData/NGP_RFBenchmark_Denis_lowerDen_524PPC_128cells_noSmoothing_denisMap_try/')
NGP_RFBenchmark_Denis_lowerDen_524PPC_128cells_noSmoothing_denisMap_try2 = dataSet('Y:/ImplicitPic1D/ImplicitData/NGP_RFBenchmark_Denis_lowerDen_524PPC_128cells_noSmoothing_denisMap_try2/')
NGP_RFBenchmark_Denis_lowerDen_524PPC_128cells_noSmoothing_denisMap_try2_Curv = dataSet('Y:/ImplicitPic1D/ImplicitData/NGP_RFBenchmark_Denis_lowerDen_524PPC_128cells_noSmoothing_denisMap_try2_Curv/')

NGP_RFBenchmark_Denis_lowerDen_1048PPC_128cells_noSmoothing_denisMap = dataSet('Y:/ImplicitPic1D/ImplicitData/NGP_RFBenchmark_Denis_lowerDen_1048PPC_128cells_noSmoothing_denisMap/')

NGP_RFBenchmark_Denis_lowerDen_2096PPC_128cells_noSmoothing_denisMap = dataSet('Y:/ImplicitPic1D/ImplicitData/NGP_RFBenchmark_Denis_lowerDen_2096PPC_128cells_noSmoothing_denisMap/')
NGP_RFBenchmark_Denis_lowerDen_4192PPC_128cells_noSmoothing_denisMap = dataSet('Y:/ImplicitPic1D/ImplicitData/NGP_RFBenchmark_Denis_lowerDen_4192PPC_128cells_noSmoothing_denisMap/')

NGP_RFBenchmark_Denis_lowerDen_524PPC_128cells_noSmoothing_sinCenter_try = dataSet('Y:/ImplicitPic1D/ImplicitData/NGP_RFBenchmark_Denis_lowerDen_524PPC_128cells_noSmoothing_sinCenter_try/')
NGP_RFBenchmark_Denis_lowerDen_524PPC_128cells_noSmoothing_doubling = dataSet('Y:/ImplicitPic1D/ImplicitData/NGP_RFBenchmark_Denis_lowerDen_524PPC_128cells_noSmoothing_doubling/')
NGP_RFBenchmark_Denis_lowerDen_524PPC_128cells_noSmoothing_sinCenter_5mmEven = dataSet('Y:/ImplicitPic1D/ImplicitData/NGP_RFBenchmark_Denis_lowerDen_524PPC_128cells_noSmoothing_sinCenter_5mmEven/')
NGP_RFBenchmark_Denis_lowerDen_524PPC_128cells_noSmoothing_sinCenter_OGTime = dataSet('Y:/ImplicitPic1D/ImplicitData/NGP_RFBenchmark_Denis_lowerDen_524PPC_128cells_noSmoothing_sinCenter_OGTime/')
NGP_RFBenchmark_Denis_lowerDen_524PPC_128cells_Smoothing_sinCenter = dataSet('Y:/ImplicitPic1D/ImplicitData/NGP_RFBenchmark_Denis_lowerDen_524PPC_128cells_Smoothing_sinCenter/')

NGP_RFBenchmark_Denis_lowerDen_524PPC_128cells_noSmoothing_sinCenter_Curv = dataSet('Y:/ImplicitPic1D/ImplicitData/NGP_RFBenchmark_Denis_lowerDen_524PPC_128cells_noSmoothing_sinCenter_Curv/')
NGP_RFBenchmark_Denis_lowerDen_524PPC_128cells_noSmoothing_sinCenter = dataSet('Y:/ImplicitPic1D/ImplicitData/NGP_RFBenchmark_Denis_lowerDen_524PPC_128cells_noSmoothing_sinCenter/')
NGP_RFBenchmark_Denis_lowerDen_1048PPC_128cells_noSmoothing_sinCenter = dataSet('Y:/ImplicitPic1D/ImplicitData/NGP_RFBenchmark_Denis_lowerDen_1048PPC_128cells_noSmoothing_sinCenter/')
NGP_RFBenchmark_Denis_lowerDen_2096PPC_128cells_noSmoothing_sinCenter = dataSet('Y:/ImplicitPic1D/ImplicitData/NGP_RFBenchmark_Denis_lowerDen_2096PPC_128cells_noSmoothing_sinCenter/')
NGP_RFBenchmark_Denis_lowerDen_4192PPC_128cells_noSmoothing_sinCenter = dataSet('Y:/ImplicitPic1D/ImplicitData/NGP_RFBenchmark_Denis_lowerDen_4192PPC_128cells_noSmoothing_sinCenter/')

NGP_RFBenchmark_Denis_lowerDen_1048PPC_128cells_noSmoothing_sinCenter_50 = dataSet('Y:/ImplicitPic1D/ImplicitData/NGP_RFBenchmark_Denis_lowerDen_1048PPC_128cells_noSmoothing_sinCenter_50/')

NGP_RFBenchmark_Denis_lowerDen_131PPC_256cells_noSmoothing = dataSet('Y:/ImplicitPic1D/ImplicitData/NGP_RFBenchmark_Denis_lowerDen_131PPC_256cells_noSmoothing/')
NGP_RFBenchmark_Denis_lowerDen_262PPC_256cells_noSmoothing = dataSet('Y:/ImplicitPic1D/ImplicitData/NGP_RFBenchmark_Denis_lowerDen_262PPC_256cells_noSmoothing/')
NGP_RFBenchmark_Denis_lowerDen_524PPC_256cells_noSmoothing = dataSet('Y:/ImplicitPic1D/ImplicitData/NGP_RFBenchmark_Denis_lowerDen_524PPC_256cells_noSmoothing/')
NGP_RFBenchmark_Denis_lowerDen_1048PPC_256cells_noSmoothing = dataSet('Y:/ImplicitPic1D/ImplicitData/NGP_RFBenchmark_Denis_lowerDen_1048PPC_256cells_noSmoothing/')
NGP_RFBenchmark_Denis_lowerDen_1048PPC_256cells_noSmoothing_PCG = dataSet('Y:/ImplicitPic1D/ImplicitData/NGP_RFBenchmark_Denis_lowerDen_1048PPC_256cells_noSmoothing_PCG/')
NGP_RFBenchmark_Denis_lowerDen_2096PPC_256cells_noSmoothing = dataSet('Y:/ImplicitPic1D/ImplicitData/NGP_RFBenchmark_Denis_lowerDen_2096PPC_256cells_noSmoothing/')

NGP_RFBenchmark_Denis_lowerDen_131PPC_512cells_noSmoothing = dataSet('Y:/ImplicitPic1D/ImplicitData/NGP_RFBenchmark_Denis_lowerDen_131PPC_512cells_noSmoothing/')
NGP_RFBenchmark_Denis_lowerDen_262PPC_512cells_noSmoothing = dataSet('Y:/ImplicitPic1D/ImplicitData/NGP_RFBenchmark_Denis_lowerDen_262PPC_512cells_noSmoothing/')
NGP_RFBenchmark_Denis_lowerDen_524PPC_512cells_noSmoothing = dataSet('Y:/ImplicitPic1D/ImplicitData/NGP_RFBenchmark_Denis_lowerDen_524PPC_512cells_noSmoothing/')
NGP_RFBenchmark_Denis_lowerDen_1048PPC_512cells_noSmoothing = dataSet('Y:/ImplicitPic1D/ImplicitData/NGP_RFBenchmark_Denis_lowerDen_1048PPC_512cells_noSmoothing/')
NGP_RFBenchmark_Denis_lowerDen_1048PPC_512cells_noSmoothing_halfTime = dataSet('Y:/ImplicitPic1D/ImplicitData/NGP_RFBenchmark_Denis_lowerDen_1048PPC_512cells_noSmoothing_halfTime/')
NGP_RFBenchmark_Denis_lowerDen_1048PPC_512cells_noSmoothing_OGTime = dataSet('Y:/ImplicitPic1D/ImplicitData/NGP_RFBenchmark_Denis_lowerDen_1048PPC_512cells_noSmoothing_OGTime/')

NGP_RFBenchmark_Denis_lowerDen_524PPC_1024cells_noSmoothing = dataSet('Y:/ImplicitPic1D/ImplicitData/NGP_RFBenchmark_Denis_lowerDen_524PPC_1024cells_noSmoothing/')
NGP_RFBenchmark_Denis_lowerDen_1048PPC_1024cells_noSmoothing = dataSet('Y:/ImplicitPic1D/ImplicitData/NGP_RFBenchmark_Denis_lowerDen_1048PPC_1024cells_noSmoothing/')
NGP_RFBenchmark_Denis_lowerDen_1048PPC_1024cells_noSmoothing_OGTime = dataSet('Y:/ImplicitPic1D/ImplicitData/NGP_RFBenchmark_Denis_lowerDen_1048PPC_1024cells_noSmoothing_OGTime/')

NGP_RFBenchmark_Denis_lowerDen_524PPC_2000cells_noSmoothing = dataSet('Y:/ImplicitPic1D/ImplicitData/NGP_RFBenchmark_Denis_lowerDen_524PPC_2000cells_noSmoothing/')
NGP_RFBenchmark_Denis_lowerDen_1048PPC_2000cells_noSmoothing = dataSet('Y:/ImplicitPic1D/ImplicitData/NGP_RFBenchmark_Denis_lowerDen_1048PPC_2000cells_noSmoothing/')
NGP_RFBenchmark_Denis_lowerDen_1048PPC_2000cells_noSmoothing_OGTime = dataSet('Y:/ImplicitPic1D/ImplicitData/NGP_RFBenchmark_Denis_lowerDen_1048PPC_2000cells_noSmoothing_OGTime/')
NGP_RFBenchmark_Denis_lowerDen_2000PPC_2500cells_noSmoothing_smallTime = dataSet('Y:/ImplicitPic1D/ImplicitData/NGP_RFBenchmark_Denis_lowerDen_1048PPC_2000cells_noSmoothing_OGTime/')

#-------------------------- CIC -----------------

CIC_RFBenchmark_Denis_131PPC_128cells = dataSet('Y:/ImplicitPic1D/ImplicitData/CIC_RFBenchmark_Denis_131PPC_128cells/')
CIC_RFBenchmark_Denis_262PPC_128cells = dataSet('Y:/ImplicitPic1D/ImplicitData/CIC_RFBenchmark_Denis_262PPC_128cells/')
CIC_RFBenchmark_Denis_262PPC_128cells_NoSmoothing = dataSet('Y:/ImplicitPic1D/ImplicitData/CIC_RFBenchmark_Denis_262PPC_128cells_NoSmoothing/')
CIC_RFBenchmark_Denis_262PPC_128cells_normTime = dataSet('Y:/ImplicitPic1D/ImplicitData/CIC_RFBenchmark_Denis_262PPC_128cells_normTime/')


CIC_RFBenchmark_Denis_131PPC_256cells_noSmoothing = dataSet('Y:/ImplicitPic1D/ImplicitData/CIC_RFBenchmark_Denis_131PPC_256cells_noSmoothing/')
CIC_RFBenchmark_Denis_262PPC_256cells_noSmoothing = dataSet('Y:/ImplicitPic1D/ImplicitData/CIC_RFBenchmark_Denis_262PPC_256cells_noSmoothing/')
CIC_RFBenchmark_Denis_524PPC_256cells_noSmoothing = dataSet('Y:/ImplicitPic1D/ImplicitData/CIC_RFBenchmark_Denis_524PPC_256cells_noSmoothing/')
CIC_RFBenchmark_Denis_1048PPC_256cells_noSmoothing = dataSet('Y:/ImplicitPic1D/ImplicitData/CIC_RFBenchmark_Denis_1048PPC_256cells_noSmoothing/')
CIC_RFBenchmark_Denis_2096PPC_256cells_noSmoothing = dataSet('Y:/ImplicitPic1D/ImplicitData/CIC_RFBenchmark_Denis_2096PPC_256cells_noSmoothing/')

CIC_RFBenchmark_Denis_2000PPC_2500cells_neg11Sec_noSmoothing = dataSet('Y:/ImplicitPic1D/ImplicitData/CIC_RFBenchmark_Denis_2000PPC_2500cells_neg11Sec_noSmoothing/')

CIC_RFBenchmark_Denis_lowerDen_131PPC_64cells_noSmoothing_sinCenter = dataSet('Y:/ImplicitPic1D/ImplicitData/CIC_RFBenchmark_Denis_lowerDen_131PPC_64cells_noSmoothing_sinCenter/')
CIC_RFBenchmark_Denis_lowerDen_50PPC_64cells_noSmoothing_sinCenter = dataSet('Y:/ImplicitPic1D/ImplicitData/CIC_RFBenchmark_Denis_lowerDen_50PPC_64cells_noSmoothing_sinCenter/')

CIC_RFBenchmark_Denis_lowerDen_1048PPC_2000cells_noSmoothing_OGTime = dataSet('Y:/ImplicitPic1D/ImplicitData/CIC_RFBenchmark_Denis_lowerDen_1048PPC_2000cells_noSmoothing_OGTime/')

CIC_RFBenchmark_Denis_131PPC_128cells_noSmoothing_sinCenter = dataSet('Y:/ImplicitPic1D/ImplicitData/CIC_RFBenchmark_Denis_131PPC_128cells_noSmoothing_sinCenter/')
CIC_RFBenchmark_Denis_262PPC_128cells_noSmoothing_sinCenter = dataSet('Y:/ImplicitPic1D/ImplicitData/CIC_RFBenchmark_Denis_262PPC_128cells_noSmoothing_sinCenter/')
CIC_RFBenchmark_Denis_524PPC_128cells_noSmoothing_sinCenter = dataSet('Y:/ImplicitPic1D/ImplicitData/CIC_RFBenchmark_Denis_524PPC_128cells_noSmoothing_sinCenter/')
CIC_RFBenchmark_Denis_1048PPC_128cells_noSmoothing_sinCenter = dataSet('Y:/ImplicitPic1D/ImplicitData/CIC_RFBenchmark_Denis_1048PPC_128cells_noSmoothing_sinCenter/')
CIC_RFBenchmark_Denis_2096PPC_128cells_noSmoothing_sinCenter = dataSet('Y:/ImplicitPic1D/ImplicitData/CIC_RFBenchmark_Denis_2096PPC_128cells_noSmoothing_sinCenter/')
CIC_RFBenchmark_Denis_4192PPC_128cells_noSmoothing_sinCenter = dataSet('Y:/ImplicitPic1D/ImplicitData/CIC_RFBenchmark_Denis_4192PPC_128cells_noSmoothing_sinCenter/')

NGP_Powis_benchmark_32ref_test = dataSet('Y:/ImplicitPic1D/ImplicitData/NGP_Powis_benchmark_32ref_test/')
ECExp_Powis_benchmark_32ref = dataSetExplicit('Y:/ImplicitPic1D/ExplicitData/ECExp_Powis_benchmark_32ref/')
Powis_32ref = np.loadtxt('ec-pic_ccp_data_for_nicolas/ccp_30cm_30mTorr_1000V_ec_refined32_ion_density.dat')


#------------- plots --------------------

plt.figure()
plt.errorbar(case1[:,0]*1e2, case1[:,4], case1[:,6], linestyle = '-', marker = '.', elinewidth=2, label = 'Benchmark')
plotAveDensity(Exp_RFBenchmark_case1, 'He+', 'Expl.')
plotAveDensity(NGP_RF_Benchmark_case1, 'He+', 'INGP')
plotAveDensity(CIC_RF_Benchmark_case1, 'He+', 'ICIC')
plt.xlim(Exp_RFBenchmark_case1.grid[0], Exp_RFBenchmark_case1.grid[-1]*1e2)
plt.xlabel('Distance (cm)', fontsize = 14)
plt.ylabel(r'He$^+$ Density (m$^{-3}$)', fontsize = 14)
plt.xticks(fontsize=12)
plt.yticks(fontsize=12)
plt.legend(loc = 'best', fontsize = 12)
plt.tight_layout()
plt.savefig('TurnerBenchmark/Case1_Exp_Imp.pdf')
plt.close()

plt.figure()
plotAveDensity(Exp_RFBenchmark_Denis_doubleTime_halfPart, 'He+', r'128 PPC, x2 $\Delta t$, 1024 cells', marker = '')
plotAveDensity(Exp_RFBenchmark_Denis_moreCells_doublePart, 'He+', '262 PPC', marker = '')
plotAveDensity(Exp_RFBenchmark_Denis_moreCells_quadPart, 'He+', '524 PPC', marker = '')
plotAveDensity(Exp_RFBenchmark_Denis_moreCells_40xPart, 'He+', '5240 PPC', marker = '')
plotAveDensity(Exp_RFBenchmark_Denis_3000Cells_20xPart_thirdsTime, 'He+', r'1747 PPC, $\times\frac{2}{3} \Delta t$, 3000 cells', marker = '')
plt.xlim(Exp_RFBenchmark_Denis_moreCells.grid[0], Exp_RFBenchmark_Denis_moreCells.grid[-1]*1e2/2)
plt.ylim(0, None)
plt.xlabel('Distance (cm)', fontsize = 14)
plt.ylabel(r'He$^+$ Density (m$^{-3}$)', fontsize = 14)
plt.xticks(fontsize=12)
plt.yticks(fontsize=12)
plt.legend(loc = 'lower right', fontsize = 12)
plt.tight_layout()
plt.savefig('Denis_RF/Exp_diffCases.pdf')
plt.savefig('Denis_RF/Exp_diffCases.png')
plt.close()

plt.figure()
plotAvePhi(Exp_RFBenchmark_Denis_doubleTime_halfPart, r'128 PPC, x2 $\Delta t$, 1024 cells', marker = '')
plotAvePhi(Exp_RFBenchmark_Denis_moreCells_doublePart, '262 PPC', marker = '')
plotAvePhi(Exp_RFBenchmark_Denis_moreCells_quadPart, '524 PPC', marker = '')
plotAvePhi(Exp_RFBenchmark_Denis_moreCells_40xPart, '5240 PPC', marker = '')
plotAvePhi(Exp_RFBenchmark_Denis_3000Cells_20xPart_thirdsTime, r'1747 PPC, $\times\frac{2}{3} \Delta t$, 3000 cells', marker = '')
plt.xlim(Exp_RFBenchmark_Denis_moreCells.grid[0], Exp_RFBenchmark_Denis_moreCells.grid[-1]*1e2/2)
plt.ylim(200, 235)
plt.xlabel('Distance (cm)', fontsize = 14)
plt.ylabel(r'Electric Potential (V)', fontsize = 14)
plt.xticks(fontsize=12)
plt.yticks(fontsize=12)
plt.legend(loc = 'lower right', fontsize = 12)
plt.tight_layout()
plt.savefig('Denis_RF/Exp_diffCases_phi.pdf')
plt.savefig('Denis_RF/Exp_diffCases_phi.png')
plt.close()

plt.figure()
plotAveDensity(Exp_RFBenchmark_Denis_3000Cells_20xPart_thirdsTime, 'He+', r'1747 PPC, $\times\frac{2}{3} \Delta t$, 3000 cells', marker = '')
plotAveDensity(NGP_RFBenchmark_Denis_2000PPC_2500cells_neg11Sec_noSmoothing, 'He+', r'INGP 2000 PPC, 2500 cells', marker = '')
plotAveDensity(CIC_RFBenchmark_Denis_2000PPC_2500cells_neg11Sec_noSmoothing, 'He+', r'ICIC 2000 PPC, 2500 cells', marker = '')
plt.xlim(Exp_RFBenchmark_Denis_moreCells.grid[0], Exp_RFBenchmark_Denis_moreCells.grid[-1]*1e2/2)
plt.ylim(0, None)
plt.xlabel('Distance (cm)', fontsize = 14)
plt.ylabel(r'He$^+$ Density (m$^{-3}$)', fontsize = 14)
plt.xticks(fontsize=12)
plt.yticks(fontsize=12)
plt.legend(loc = 'lower right', fontsize = 12)
plt.tight_layout()
plt.savefig('Denis_RF/Exp_Imp_highPressure.pdf')
plt.savefig('Denis_RF/Exp_Imp_highPressure.png')
plt.close()

plt.figure()
plotAvePhi(Exp_RFBenchmark_Denis_3000Cells_20xPart_thirdsTime, r'1747 PPC, $\times\frac{2}{3} \Delta t$, 3000 cells', marker = '')
plotAvePhi(NGP_RFBenchmark_Denis_2000PPC_2500cells_neg11Sec_noSmoothing, r'INGP 2000 PPC, 2500 cells', marker = '')
plotAvePhi(CIC_RFBenchmark_Denis_2000PPC_2500cells_neg11Sec_noSmoothing, r'ICIC 2000 PPC, 2500 cells', marker = '')
plt.xlim(Exp_RFBenchmark_Denis_moreCells.grid[0], Exp_RFBenchmark_Denis_moreCells.grid[-1]*1e2/2)
plt.ylim(200, 235)
plt.xlabel('Distance (cm)', fontsize = 14)
plt.ylabel(r'Electric Potential (V)', fontsize = 14)
plt.xticks(fontsize=12)
plt.yticks(fontsize=12)
plt.legend(loc = 'lower right', fontsize = 12)
plt.tight_layout()
plt.savefig('Denis_RF/Exp_Imp_highPressure_phi.pdf')
plt.savefig('Denis_RF/Exp_Imp_highPressure_phi.png')
plt.close()



plt.figure()
plotAveEPF(Exp_RFBenchmark_Denis_moreCells, 'e', label = '131 PPC')
plotAveEPF(Exp_RFBenchmark_Denis_moreCells_40xPart, 'e', label = '5240 PPC')
plotAveEPF(Exp_RFBenchmark_Denis_doubleTime_halfPart, 'e', label = r'128 PPC, x2 $\Delta t$, 1024 cells')
plt.ylim(0,None)
plt.xlim(0.1,150)
plt.xlabel('Energy (eV)', fontsize = 14)
plt.ylabel(r'EPDF (eV$^{-3/2}$)', fontsize = 14)
plt.xticks(fontsize=12)
plt.yticks(fontsize=12)
plt.legend(loc = 'best', fontsize = 12)
plt.tight_layout()
plt.savefig('Denis_RF/EPF_Exp_comp.pdf')
plt.savefig('Denis_RF/EPF_Exp_comp.png')
plt.close()

plt.figure()
plotAveDensity(Exp_RFBenchmark_Denis_moreCells_40xPart, 'He+', 'Ref')
plotAveDensity(NGP_RFBenchmark_Denis_262PPC_128cells_noSmoothing, 'He+', '262 PPC')
plotAveDensity(NGP_RFBenchmark_Denis_524PPC_128cells_noSmoothing, 'He+', '524 PPC')
plt.xlim(Exp_RFBenchmark_Denis_moreCells.grid[0], Exp_RFBenchmark_Denis_moreCells.grid[-1]*1e2)
plt.ylim(0, None)
plt.xlabel('Distance (cm)', fontsize = 14)
plt.ylabel(r'He$^+$ Density (m$^{-3}$)', fontsize = 14)
plt.xticks(fontsize=12)
plt.yticks(fontsize=12)
plt.legend(loc = 'lower right', fontsize = 12)
plt.tight_layout()
plt.savefig('Denis_RF/NGP_128cells_even.pdf')
plt.savefig('Denis_RF/NGP_128cells_even.png')
plt.close()

plt.figure()
plotAveDensity(NGP_RFBenchmark_Denis_2000PPC_2500cells_neg11Sec_noSmoothing, 'He+', '2000 PPC, 2500 Cells', linestyle = '-', marker = '')
plotAveDensity(NGP_RFBenchmark_Denis_2096PPC_256cells_noSmoothing, 'He+', '2096 PPC, 256 cells', marker = '')
plotAveDensity(NGP_RFBenchmark_Denis_2096PPC_256cells_noSmoothing_OGTime, 'He+', r'2096 PPC, 256 cells, Expl. $\Delta t$', marker = '')
plotAveDensity(NGP_RFBenchmark_Denis_1048PPC_1024cells_noSmoothing, 'He+', r'1048 PPC, 1024 Cells', marker = '')
plotAveDensity(NGP_RFBenchmark_Denis_1048PPC_1024cells_noSmoothing_OGTime, 'He+', r'1048 PPC, 1024 Cells, Expl. $\Delta t$', marker = '')
# plotAveDensity(NGP_RFBenchmark_Denis_1024PPC_2000cells_noSmoothing, 'He+', r'1024 PPC, 2000 Cells, Expl. $\Delta t$', linestyle = '-', marker = '')
# plotAveDensity(NGP_RFBenchmark_Denis_1024PPC_2500cells_neg11Sec_noSmoothing, 'He+', r'NGP 1024 PPC, 2500 Cells, lower $\Delta t$')
plt.xlim(Exp_RFBenchmark_Denis_moreCells.grid[0], Exp_RFBenchmark_Denis_moreCells.grid[-1]*1e2/2)
plt.ylim(0, None)
plt.xlabel('Distance (cm)', fontsize = 14)
plt.ylabel(r'He$^+$ Density (m$^{-3}$)', fontsize = 14)
plt.xticks(fontsize=12)
plt.yticks(fontsize=12)
plt.legend(loc = 'lower right', fontsize = 12)
plt.tight_layout()
plt.savefig('Denis_RF/NGP_timeChange_even.pdf')
plt.savefig('Denis_RF/NGP_timeChange_even.png')
plt.close()

plt.figure()
plotAveDensity(Exp_RFBenchmark_Denis_3000Cells_20xPart_thirdsTime, 'He+', 'Expl. High Res', linestyle = '-', marker = '')
plotAveDensity(NGP_RFBenchmark_Denis_1048PPC_1024cells_noSmoothing_OGTime, 'He+', r'1048 PPC, 1024 Cells, Expl. $\Delta t$', marker = '')
plotAveDensity(NGP_RFBenchmark_Denis_1024PPC_2000cells_noSmoothing, 'He+', r'1024 PPC, 2000 Cells, Expl. $\Delta t$', linestyle = '-', marker = '')
plotAveDensity(NGP_RFBenchmark_Denis_1024PPC_2500cells_neg11Sec_noSmoothing, 'He+', r'NGP 1024 PPC, 2500 Cells, lower $\Delta t$', marker = '')
plt.xlim(Exp_RFBenchmark_Denis_moreCells.grid[0], Exp_RFBenchmark_Denis_moreCells.grid[-1]*1e2/2)
plt.ylim(0, None)
plt.xlabel('Distance (cm)', fontsize = 14)
plt.ylabel(r'He$^+$ Density (m$^{-3}$)', fontsize = 14)
plt.xticks(fontsize=12)
plt.yticks(fontsize=12)
plt.legend(loc = 'lower right', fontsize = 12)
plt.tight_layout()
plt.savefig('Denis_RF/NGP_high_Res.pdf')
plt.savefig('Denis_RF/NGP_high_Res.png')
plt.close()

plt.figure()
plotAvePhi(Exp_RFBenchmark_Denis_3000Cells_20xPart_thirdsTime, 'Expl. High Res', linestyle = '-', marker = '')
plotAvePhi(NGP_RFBenchmark_Denis_1048PPC_1024cells_noSmoothing_OGTime,  r'1048 PPC, 1024 Cells, Expl. $\Delta t$', marker = '')
plotAvePhi(NGP_RFBenchmark_Denis_1024PPC_2000cells_noSmoothing, r'1024 PPC, 2000 Cells, Expl. $\Delta t$', linestyle = '-', marker = '')
plotAvePhi(NGP_RFBenchmark_Denis_1024PPC_2500cells_neg11Sec_noSmoothing, r'NGP 1024 PPC, 2500 Cells, lower $\Delta t$', marker = '')
plt.xlim(Exp_RFBenchmark_Denis_moreCells.grid[0], Exp_RFBenchmark_Denis_moreCells.grid[-1]*1e2/2)
plt.ylim(0, None)
plt.xlabel('Distance (cm)', fontsize = 14)
plt.ylabel(r'He$^+$ Density (m$^{-3}$)', fontsize = 14)
plt.xticks(fontsize=12)
plt.yticks(fontsize=12)
plt.legend(loc = 'lower right', fontsize = 12)
plt.tight_layout()
plt.savefig('Denis_RF/NGP_high_Res_phi.pdf')
plt.savefig('Denis_RF/NGP_high_Res_phi.png')
plt.close()

plt.figure()
plotAveDensity(NGP_RFBenchmark_Denis_2000PPC_2500cells_neg11Sec_noSmoothing, 'He+', '2000 PPC, 2500 Cells', linestyle = '-', marker = '')
plotAveDensity(NGP_RFBenchmark_Denis_524PPC_256cells_noSmoothing, 'He+', '524 PPC', marker = '.')
plotAveDensity(NGP_RFBenchmark_Denis_1048PPC_256cells_noSmoothing, 'He+', '1048 PPC', marker = '.')
plotAveDensity(NGP_RFBenchmark_Denis_2096PPC_256cells_noSmoothing, 'He+', '2096 PPC', marker = '.')
plotAveDensity(NGP_RFBenchmark_Denis_4192PPC_256cells_noSmoothing, 'He+', '4192 PPC', marker = '.')
# plotAveDensity(NGP_RFBenchmark_Denis_2096PPC_256cells_noSmoothing_OGTime, 'He+', '2096 PPC OG Time')
# plotAveDensity(NGP_RFBenchmark_Denis_1048PPC_1024cells_noSmoothing_OGTime, 'He+', '1048 PPC 1024 cells OG Time')
plt.xlim(Exp_RFBenchmark_Denis_moreCells.grid[0], Exp_RFBenchmark_Denis_moreCells.grid[-1]*1e2/2)
plt.ylim(0, None)
plt.xlabel('Distance (cm)', fontsize = 14)
plt.ylabel(r'He$^+$ Density (m$^{-3}$)', fontsize = 14)
plt.xticks(fontsize=12)
plt.yticks(fontsize=12)
plt.legend(loc = 'lower right', fontsize = 12)
plt.tight_layout()
plt.savefig('Denis_RF/NGP_256cells_even.pdf')
plt.savefig('Denis_RF/NGP_256cells_even.png')
plt.close()

plt.figure()
plotAvePhi(NGP_RFBenchmark_Denis_2000PPC_2500cells_neg11Sec_noSmoothing,'2000 PPC, 2500 Cells', linestyle = '-', marker = '')
plotAvePhi(NGP_RFBenchmark_Denis_524PPC_256cells_noSmoothing,'524 PPC', marker = '.')
plotAvePhi(NGP_RFBenchmark_Denis_1048PPC_256cells_noSmoothing, '1048 PPC', marker = '.')
plotAvePhi(NGP_RFBenchmark_Denis_2096PPC_256cells_noSmoothing, '2096 PPC', marker = '.')
plotAvePhi(NGP_RFBenchmark_Denis_4192PPC_256cells_noSmoothing,'4192 PPC', marker = '.')
# plotAveDensity(NGP_RFBenchmark_Denis_2096PPC_256cells_noSmoothing_OGTime, 'He+', '2096 PPC OG Time')
# plotAveDensity(NGP_RFBenchmark_Denis_1048PPC_1024cells_noSmoothing_OGTime, 'He+', '1048 PPC 1024 cells OG Time')
plt.xlim(Exp_RFBenchmark_Denis_moreCells.grid[0], Exp_RFBenchmark_Denis_moreCells.grid[-1]*1e2/2)
plt.ylim(210, 232)
plt.xlabel('Distance (cm)', fontsize = 14)
plt.ylabel(r'Electric Potential (V)', fontsize = 14)
plt.xticks(fontsize=12)
plt.yticks(fontsize=12)
plt.legend(loc = 'lower right', fontsize = 12)
plt.tight_layout()
plt.savefig('Denis_RF/NGP_256cells_even_phi.pdf')
plt.savefig('Denis_RF/NGP_256cells_even_phi.png')
plt.close()



# plt.figure()
# plotAvePhi(Exp_RFBenchmark_Denis_moreCells_40xPart, '5240 PPC Expl.', linestyle = '-', marker = '')
# plotAvePhi(NGP_RFBenchmark_Denis_524PPC_256cells_noSmoothing, '524 PPC', marker = '.')
# plotAvePhi(NGP_RFBenchmark_Denis_1048PPC_256cells_noSmoothing, '1048 PPC', marker = '.')
# plotAvePhi(NGP_RFBenchmark_Denis_2096PPC_256cells_noSmoothing, '2096 PPC', marker = '.')
# plotAvePhi(NGP_RFBenchmark_Denis_4192PPC_256cells_noSmoothing, '4192 PPC', marker = '.')
# # plotAveDensity(NGP_RFBenchmark_Denis_2096PPC_256cells_noSmoothing_OGTime, 'He+', '2096 PPC OG Time')
# # plotAveDensity(NGP_RFBenchmark_Denis_1048PPC_1024cells_noSmoothing_OGTime, 'He+', '1048 PPC 1024 cells OG Time')
# plt.xlim(Exp_RFBenchmark_Denis_moreCells.grid[0], Exp_RFBenchmark_Denis_moreCells.grid[-1]*1e2/2)
# plt.ylim(215, 233)
# plt.xlabel('Distance (cm)', fontsize = 14)
# plt.ylabel(r'Electric Potential (V)', fontsize = 14)
# plt.xticks(fontsize=12)
# plt.yticks(fontsize=12)
# plt.legend(loc = 'lower right', fontsize = 12)
# plt.tight_layout()
# plt.savefig('Denis_RF/NGP_256cells_even_phi.pdf')
# plt.savefig('Denis_RF/NGP_256cells_even_phi.png')
# plt.close()

plt.figure()
plotAveEPF(Exp_RFBenchmark_Denis_moreCells_40xPart, 'He+', label = '5240 PPC Expl.')
plotAveEPF(NGP_RFBenchmark_Denis_524PPC_256cells_noSmoothing, 'He+', label = '524 PPC')
plotAveEPF(NGP_RFBenchmark_Denis_1048PPC_256cells_noSmoothing, 'He+', label = '1048 PPC')
plotAveEPF(NGP_RFBenchmark_Denis_2096PPC_256cells_noSmoothing, 'He+', label = '2096 PPC')
plotAveEPF(NGP_RFBenchmark_Denis_4192PPC_256cells_noSmoothing, 'He+', label = '4192 PPC')
# plotAveDensity(NGP_RFBenchmark_Denis_2096PPC_256cells_noSmoothing_OGTime, 'He+', '2096 PPC OG Time')
# plotAveDensity(NGP_RFBenchmark_Denis_1048PPC_1024cells_noSmoothing_OGTime, 'He+', '1048 PPC 1024 cells OG Time')
plt.xlabel('Electron energy (eV)', fontsize = 14)
plt.xticks(fontsize=12)
plt.yticks(fontsize=12)
plt.legend(loc = 'upper right', fontsize = 12)
plt.tight_layout()
plt.savefig('Denis_RF/NGP_256cells_even_EPF.pdf')
plt.savefig('Denis_RF/NGP_256cells_even_EPF.png')
plt.close()

plt.figure()
plotAveDensity(Exp_RFBenchmark_Denis_moreCells_40xPart, 'He+', '5240 PPC Expl.')
plotAveDensity(CIC_RFBenchmark_Denis_524PPC_256cells_noSmoothing, 'He+', '524 PPC')
plotAveDensity(CIC_RFBenchmark_Denis_1048PPC_256cells_noSmoothing, 'He+', '1048 PPC')
plotAveDensity(CIC_RFBenchmark_Denis_2096PPC_256cells_noSmoothing, 'He+', '2096 PPC')
plt.xlim(Exp_RFBenchmark_Denis_moreCells.grid[0], Exp_RFBenchmark_Denis_moreCells.grid[-1]*1e2)
plt.ylim(0, None)
plt.xlabel('Distance (cm)', fontsize = 14)
plt.ylabel(r'He$^+$ Density (m$^{-3}$)', fontsize = 14)
plt.xticks(fontsize=12)
plt.yticks(fontsize=12)
plt.legend(loc = 'lower right', fontsize = 12)
plt.tight_layout()
plt.savefig('Denis_RF/CIC_256cells_even.pdf')
plt.savefig('Denis_RF/CIC_256cells_even.png')
plt.close()

plt.figure()
plotAveDensity(NGP_RFBenchmark_Denis_2000PPC_2500cells_neg11Sec_noSmoothing,'He+', '2000 PPC, 2500 Cells')
plotAveDensity(NGP_RFBenchmark_Denis_131PPC_128cells_noSmoothing_sinCenter, 'He+', '131 PPC')
plotAveDensity(NGP_RFBenchmark_Denis_262PPC_128cells_noSmoothing_sinCenter, 'He+', '262 PPC')
plotAveDensity(NGP_RFBenchmark_Denis_524PPC_128cells_noSmoothing_sinCenter, 'He+', '524 PPC')
plotAveDensity(NGP_RFBenchmark_Denis_1048PPC_128cells_noSmoothing_sinCenter, 'He+', '1048 PPC')
plotAveDensity(NGP_RFBenchmark_Denis_2096PPC_128cells_noSmoothing_sinCenter, 'He+', '2096 PPC')
plt.xlim(Exp_RFBenchmark_Denis_moreCells.grid[0], Exp_RFBenchmark_Denis_moreCells.grid[-1]*1e2/2)
plt.ylim(0, None)
plt.xlabel('Distance (cm)', fontsize = 14)
plt.ylabel(r'He$^+$ Density (m$^{-3}$)', fontsize = 14)
plt.xticks(fontsize=12)
plt.yticks(fontsize=12)
plt.legend(loc = 'lower right', fontsize = 12)
plt.tight_layout()
plt.savefig('Denis_RF/NGP_128cells_noneven.pdf')
plt.savefig('Denis_RF/NGP_128cells_noneven.png')
plt.close()

plt.figure()
plotAvePhi(NGP_RFBenchmark_Denis_2000PPC_2500cells_neg11Sec_noSmoothing, '2000 PPC, 2500 Cells')
plotAvePhi(NGP_RFBenchmark_Denis_131PPC_128cells_noSmoothing_sinCenter, '131 PPC')
plotAvePhi(NGP_RFBenchmark_Denis_262PPC_128cells_noSmoothing_sinCenter, '262 PPC')
plotAvePhi(NGP_RFBenchmark_Denis_524PPC_128cells_noSmoothing_sinCenter, '524 PPC')
plotAvePhi(NGP_RFBenchmark_Denis_1048PPC_128cells_noSmoothing_sinCenter, '1048 PPC')
plotAvePhi(NGP_RFBenchmark_Denis_2096PPC_128cells_noSmoothing_sinCenter, '2096 PPC')
plt.xlim(Exp_RFBenchmark_Denis_moreCells.grid[0], Exp_RFBenchmark_Denis_moreCells.grid[-1]*1e2/2)
plt.ylim(200, 235)
plt.xlabel('Distance (cm)', fontsize = 14)
plt.ylabel(r'He$^+$ Density (m$^{-3}$)', fontsize = 14)
plt.xticks(fontsize=12)
plt.yticks(fontsize=12)
plt.legend(loc = 'lower right', fontsize = 12)
plt.tight_layout()
plt.savefig('Denis_RF/NGP_128cells_noneven_phi.pdf')
plt.savefig('Denis_RF/NGP_128cells_noneven_phi.png')
plt.close()

plt.figure()
plotAveDensity(Exp_RFBenchmark_Denis_moreCells_40xPart, 'He+', '5240 PPC Expl.')
plotAveDensity(NGP_RFBenchmark_Denis_1048PPC_128cells_noSmoothing_sinCenter, 'He+', '1048 PPC')
plotAveDensity(NGP_RFBenchmark_Denis_1048PPC_128cells_Smoothing_sinCenter, 'He+', '1048 PPC w/smoothing')
plt.xlim(Exp_RFBenchmark_Denis_moreCells.grid[0], Exp_RFBenchmark_Denis_moreCells.grid[-1]*1e2/2)
plt.ylim(0, None)
plt.xlabel('Distance (cm)', fontsize = 14)
plt.ylabel(r'He$^+$ Density (m$^{-3}$)', fontsize = 14)
plt.xticks(fontsize=12)
plt.yticks(fontsize=12)
plt.legend(loc = 'lower right', fontsize = 12)
plt.tight_layout()
plt.savefig('Denis_RF/NGP_128cells_noneven_smoothComp.pdf')
plt.savefig('Denis_RF/NGP_128cells_noneven_smoothComp.png')
plt.close()

plt.figure()
plotAveDensity(Exp_RFBenchmark_Denis_moreCells_40xPart, 'He+', '5240 PPC Expl.')
plotAveDensity(NGP_RFBenchmark_Denis_131PPC_128cells_Smoothing_sinCenter, 'He+', '131 PPC')
plotAveDensity(NGP_RFBenchmark_Denis_262PPC_128cells_Smoothing_sinCenter, 'He+', '262 PPC')
plotAveDensity(NGP_RFBenchmark_Denis_524PPC_128cells_Smoothing_sinCenter, 'He+', '524 PPC')
plotAveDensity(NGP_RFBenchmark_Denis_1048PPC_128cells_Smoothing_sinCenter, 'He+', '1048 PPC')
plt.xlim(Exp_RFBenchmark_Denis_moreCells.grid[0], Exp_RFBenchmark_Denis_moreCells.grid[-1]*1e2/2)
plt.ylim(0, None)
plt.xlabel('Distance (cm)', fontsize = 14)
plt.ylabel(r'He$^+$ Density (m$^{-3}$)', fontsize = 14)
plt.xticks(fontsize=12)
plt.yticks(fontsize=12)
plt.legend(loc = 'lower right', fontsize = 12)
plt.tight_layout()
plt.savefig('Denis_RF/NGP_128cells_noneven_smooth.pdf')
plt.savefig('Denis_RF/NGP_128cells_noneven_smooth.png')
plt.close()

plt.figure()
plotAveDensity(CIC_RFBenchmark_Denis_2000PPC_2500cells_neg11Sec_noSmoothing, 'He+', r'2000 PPC, 2500 cells')
plotAveDensity(CIC_RFBenchmark_Denis_131PPC_128cells_noSmoothing_sinCenter, 'He+', '131 PPC')
plotAveDensity(CIC_RFBenchmark_Denis_262PPC_128cells_noSmoothing_sinCenter, 'He+', '262 PPC')
plotAveDensity(CIC_RFBenchmark_Denis_524PPC_128cells_noSmoothing_sinCenter, 'He+', '524 PPC')
plotAveDensity(CIC_RFBenchmark_Denis_1048PPC_128cells_noSmoothing_sinCenter, 'He+', '1048 PPC')
plotAveDensity(CIC_RFBenchmark_Denis_2096PPC_128cells_noSmoothing_sinCenter, 'He+', '2096 PPC')
plotAveDensity(CIC_RFBenchmark_Denis_4192PPC_128cells_noSmoothing_sinCenter, 'He+', '4192 PPC')
plt.xlim(Exp_RFBenchmark_Denis_moreCells.grid[0], Exp_RFBenchmark_Denis_moreCells.grid[-1]*1e2/2)
plt.ylim(0, None)
plt.xlabel('Distance (cm)', fontsize = 14)
plt.ylabel(r'He$^+$ Density (m$^{-3}$)', fontsize = 14)
plt.xticks(fontsize=12)
plt.yticks(fontsize=12)
plt.legend(loc = 'lower right', fontsize = 12)
plt.tight_layout()
plt.savefig('Denis_RF/CIC_128cells_noneven.pdf')
plt.savefig('Denis_RF/CIC_128cells_noneven.png')
plt.close()


# ------------------- lower pressure -------------------------------

plt.figure()
plotAveDensity(Exp_RFBenchmark_Denis_lowerDen_doubleTime_1024Cells_128PPC, 'He+', r'128 PPC, x2 $\Delta t$, 1024 cells', marker = '')
plotAveDensity(Exp_RFBenchmark_Denis_moreCells_lowerDen_doublePart, 'He+', '262 PPC', marker = '')
plotAveDensity(Exp_RFBenchmark_Denis_moreCells_lowerDen_quadPart, 'He+', '524 PPC', marker = '')
plotAveDensity(Exp_RFBenchmark_Denis_moreCells_lowerDen_10xPart, 'He+', '1310 PPC', marker = '')
plotAveDensity(Exp_RFBenchmark_Denis_moreCells_lowerDen_20xPart, 'He+', r'2620 PPC', marker = '')
plotAveDensity(Exp_RFBenchmark_Denis_moreCells_lowerDen_20xPart_3000cells_thirdsTime, 'He+', r'1747 PPC, 3000 cells, $\frac{2}{3} \Delta t$', marker = '')
plt.xlim(Exp_RFBenchmark_Denis_moreCells_lowerDen.grid[0], Exp_RFBenchmark_Denis_moreCells_lowerDen.grid[-1]*1e2/2)
plt.ylim(0, None)
plt.xlabel('Distance (cm)', fontsize = 14)
plt.ylabel(r'He$^+$ Density (m$^{-3}$)', fontsize = 14)
plt.xticks(fontsize=12)
plt.yticks(fontsize=12)
plt.legend(loc = 'lower right', fontsize = 12)
plt.tight_layout()
plt.savefig('Denis_RF/Exp_diffCases_lowDen.pdf')
plt.savefig('Denis_RF/Exp_diffCases_lowDen.png')
plt.close()

plt.figure()
plotAvePhi(Exp_RFBenchmark_Denis_lowerDen_doubleTime_1024Cells_128PPC, r'128 PPC, x2 $\Delta t$, 1024 cells', marker = '')
plotAvePhi(Exp_RFBenchmark_Denis_moreCells_lowerDen_doublePart, '262 PPC', marker = '')
plotAvePhi(Exp_RFBenchmark_Denis_moreCells_lowerDen_quadPart, '524 PPC', marker = '')
plotAvePhi(Exp_RFBenchmark_Denis_moreCells_lowerDen_10xPart, '1310 PPC', marker = '')
plotAvePhi(Exp_RFBenchmark_Denis_moreCells_lowerDen_20xPart, r'2620 PPC', marker = '')
plotAvePhi(Exp_RFBenchmark_Denis_moreCells_lowerDen_20xPart_3000cells_thirdsTime, r'1747 PPC, 3000 cells, $\frac{2}{3} \Delta t$', marker = '')
plt.xlim(Exp_RFBenchmark_Denis_moreCells_lowerDen.grid[0], Exp_RFBenchmark_Denis_moreCells_lowerDen.grid[-1]*1e2/2)
plt.ylim(220, 264)
plt.xlabel('Distance (cm)', fontsize = 14)
plt.ylabel(r'Electric Potential (V)', fontsize = 14)
plt.xticks(fontsize=12)
plt.yticks(fontsize=12)
plt.legend(loc = 'lower right', fontsize = 12)
plt.tight_layout()
plt.savefig('Denis_RF/Exp_diffCases_lowDen_phi.pdf')
plt.savefig('Denis_RF/Exp_diffCases_lowDen_phi.png')
plt.close()

plt.figure()
plotAveDensity(NGP_RFBenchmark_Denis_lowerDen_2000PPC_2500cells_noSmoothing_smallTime, 'He+', '2000 PPC, 2500 Cells')
plotAveDensity(NGP_RFBenchmark_Denis_lowerDen_262PPC_256cells_noSmoothing, 'He+', '262 PPC')
plotAveDensity(NGP_RFBenchmark_Denis_lowerDen_524PPC_256cells_noSmoothing, 'He+', '524 PPC')
plotAveDensity(NGP_RFBenchmark_Denis_lowerDen_1048PPC_256cells_noSmoothing, 'He+', '1048 PPC')
plotAveDensity(NGP_RFBenchmark_Denis_lowerDen_2096PPC_256cells_noSmoothing, 'He+', '2096 PPC')
plt.xlim(Exp_RFBenchmark_Denis_moreCells_lowerDen.grid[0], Exp_RFBenchmark_Denis_moreCells_lowerDen.grid[-1]*1e2/2)
plt.ylim(0, None)
plt.xlabel('Distance (cm)', fontsize = 14)
plt.ylabel(r'He$^+$ Density (m$^{-3}$)', fontsize = 14)
plt.xticks(fontsize=12)
plt.yticks(fontsize=12)
plt.legend(loc = 'lower right', fontsize = 12)
plt.tight_layout()
plt.savefig('Denis_RF/NGP_lowPress_256cells_even.pdf')
plt.savefig('Denis_RF/NGP_lowPress_256cells_even.png')
plt.close()

plt.figure()
plotAvePhi(NGP_RFBenchmark_Denis_lowerDen_2000PPC_2500cells_noSmoothing_smallTime, '2000 PPC, 2500 Cells')
plotAvePhi(NGP_RFBenchmark_Denis_lowerDen_262PPC_256cells_noSmoothing, '262 PPC')
plotAvePhi(NGP_RFBenchmark_Denis_lowerDen_524PPC_256cells_noSmoothing, '524 PPC')
plotAvePhi(NGP_RFBenchmark_Denis_lowerDen_1048PPC_256cells_noSmoothing, '1048 PPC')
plotAvePhi(NGP_RFBenchmark_Denis_lowerDen_2096PPC_256cells_noSmoothing, '2096 PPC')
plt.xlim(Exp_RFBenchmark_Denis_moreCells_lowerDen.grid[0], Exp_RFBenchmark_Denis_moreCells_lowerDen.grid[-1]*1e2/2)
plt.ylim(220, 264)
plt.xlabel('Distance (cm)', fontsize = 14)
plt.ylabel(r'Electric Potential (V)', fontsize = 14)
plt.xticks(fontsize=12)
plt.yticks(fontsize=12)
plt.legend(loc = 'lower right', fontsize = 12)
plt.tight_layout()
plt.savefig('Denis_RF/NGP_lowPress_256cells_even_phi.pdf')
plt.savefig('Denis_RF/NGP_lowPress_256cells_even_phi.png')
plt.close()

plt.figure()
plotAveEPF(Exp_RFBenchmark_Denis_moreCells_lowerDen_20xPart, 'e',  label = '2620 PPC Expl.')
plotAveEPF(NGP_RFBenchmark_Denis_lowerDen_262PPC_256cells_noSmoothing, 'e', label = '262 PPC')
plotAveEPF(NGP_RFBenchmark_Denis_lowerDen_524PPC_256cells_noSmoothing, 'e',  label = '524 PPC')
plotAveEPF(NGP_RFBenchmark_Denis_lowerDen_1048PPC_256cells_noSmoothing, 'e', label = '1048 PPC')
plotAveEPF(NGP_RFBenchmark_Denis_lowerDen_2096PPC_256cells_noSmoothing, 'e', label = '2096 PPC')
plt.xlabel('Electron Energy (eV)', fontsize = 14)
plt.ylabel(r'Electron PDF (eV$^{-3/2}$)', fontsize = 14)
plt.xticks(fontsize=12)
plt.yticks(fontsize=12)
plt.legend(loc = 'upper right', fontsize = 12)
plt.tight_layout()
plt.savefig('Denis_RF/NGP_lowPress_256cells_even_EPF.pdf')
plt.savefig('Denis_RF/NGP_lowPress_256cells_even_EPF.png')
plt.close()

plt.figure()
plotAveDensity(Exp_RFBenchmark_Denis_moreCells_lowerDen_20xPart, 'He+', '2620 PPC Expl.', marker = '')
# plotAveDensity(NGP_RFBenchmark_Denis_lowerDen_1048PPC_2000cells_noSmoothing, 'He+', r'INGP 1048 PPC, 2000 cells', marker = '')
# plotAveDensity(NGP_RFBenchmark_Denis_lowerDen_1048PPC_2000cells_noSmoothing_OGTime, 'He+', r'INGP 1048 PPC, 2000 cells', marker = '')
plotAveDensity(NGP_RFBenchmark_Denis_lowerDen_2000PPC_2500cells_noSmoothing_smallTime, 'He+', 'INGP 2000 PPC, 2500 cells', marker = '')
plt.xlim(Exp_RFBenchmark_Denis_moreCells_lowerDen.grid[0], Exp_RFBenchmark_Denis_moreCells_lowerDen.grid[-1]*1e2/2)
plt.ylim(0, None)
plt.xlabel('Distance (cm)', fontsize = 14)
plt.ylabel(r'He$^+$ Density (m$^{-3}$)', fontsize = 14)
plt.xticks(fontsize=12)
plt.yticks(fontsize=12)
plt.legend(loc = 'lower right', fontsize = 12)
plt.tight_layout()
plt.savefig('Denis_RF/NGP_lowPress_2000cells_even.pdf')
plt.savefig('Denis_RF/NGP_lowPress_2000cells_even.png')
plt.close()

plt.figure()
plotAvePhi(Exp_RFBenchmark_Denis_moreCells_lowerDen_20xPart, '2620 PPC Expl.')
# plotAvePhi(CIC_RFBenchmark_Denis_lowerDen_1048PPC_2000cells_noSmoothing_OGTime, r'CIC, 1048 PPC, 2000 cells')
plotAvePhi(NGP_RFBenchmark_Denis_lowerDen_2000PPC_2500cells_noSmoothing_smallTime,'INGP 2000 PPC, 2500 cells')
plt.xlim(Exp_RFBenchmark_Denis_moreCells_lowerDen.grid[0], Exp_RFBenchmark_Denis_moreCells_lowerDen.grid[-1]*1e2/2)
plt.ylim(220, 264)
plt.xlabel('Distance (cm)', fontsize = 14)
plt.ylabel(r'Electric Potential (V)', fontsize = 14)
plt.xticks(fontsize=12)
plt.yticks(fontsize=12)
plt.legend(loc = 'lower right', fontsize = 12)
plt.tight_layout()
plt.savefig('Denis_RF/NGP_lowPress_2000cells_even_phi.pdf')
plt.savefig('Denis_RF/NGP_lowPress_2000cells_even_phi.png')
plt.close()

plt.figure()
plotAveDensity(Exp_RFBenchmark_Denis_moreCells_lowerDen_20xPart, 'He+', 'Ref')
plotAveDensity(NGP_RFBenchmark_Denis_lowerDen_131PPC_512cells_noSmoothing, 'He+', '131 PPC')
plotAveDensity(NGP_RFBenchmark_Denis_lowerDen_262PPC_512cells_noSmoothing, 'He+', '262 PPC')
plotAveDensity(NGP_RFBenchmark_Denis_lowerDen_524PPC_512cells_noSmoothing, 'He+', '524 PPC')
plotAveDensity(NGP_RFBenchmark_Denis_lowerDen_1048PPC_512cells_noSmoothing, 'He+', '1048 PPC')
plt.xlim(Exp_RFBenchmark_Denis_moreCells_lowerDen.grid[0], Exp_RFBenchmark_Denis_moreCells_lowerDen.grid[-1]*1e2)
plt.ylim(0, None)
plt.xlabel('Distance (cm)', fontsize = 14)
plt.ylabel(r'He$^+$ Density (m$^{-3}$)', fontsize = 14)
plt.xticks(fontsize=12)
plt.yticks(fontsize=12)
plt.legend(loc = 'lower right', fontsize = 12)
plt.tight_layout()
plt.savefig('Denis_RF/NGP_lowPress_512cells_even.pdf')
plt.savefig('Denis_RF/NGP_lowPress_512cells_even.png')
plt.close()

plt.figure()
plotAveDensity(NGP_RFBenchmark_Denis_lowerDen_2000PPC_2500cells_noSmoothing_smallTime, 'He+', '2000 PPC, 2500 Cells')
plotAveDensity(NGP_RFBenchmark_Denis_lowerDen_524PPC_128cells_noSmoothing_sinCenter, 'He+', '524 PPC')
plotAveDensity(NGP_RFBenchmark_Denis_lowerDen_1048PPC_128cells_noSmoothing_sinCenter, 'He+', '1048 PPC')
plotAveDensity(NGP_RFBenchmark_Denis_lowerDen_2096PPC_128cells_noSmoothing_sinCenter, 'He+', '2096 PPC')
plotAveDensity(NGP_RFBenchmark_Denis_lowerDen_4192PPC_128cells_noSmoothing_sinCenter, 'He+', '4192 PPC')
plt.xlim(Exp_RFBenchmark_Denis_moreCells_lowerDen.grid[0], Exp_RFBenchmark_Denis_moreCells_lowerDen.grid[-1]*1e2/2)
plt.ylim(0, None)
plt.xlabel('Distance (cm)', fontsize = 14)
plt.ylabel(r'He$^+$ Density (m$^{-3}$)', fontsize = 14)
plt.xticks(fontsize=12)
plt.yticks(fontsize=12)
plt.legend(loc = 'lower right', fontsize = 12)
plt.tight_layout()
plt.savefig('Denis_RF/NGP_lowPress_128cells_noneven.pdf')
plt.savefig('Denis_RF/NGP_lowPress_128cells_noneven.png')
plt.close()


plt.figure()
plotAvePhi(NGP_RFBenchmark_Denis_lowerDen_2000PPC_2500cells_noSmoothing_smallTime, '2000 PPC, 2500 Cells')
plotAvePhi(NGP_RFBenchmark_Denis_lowerDen_524PPC_128cells_noSmoothing_sinCenter, '524 PPC')
plotAvePhi(NGP_RFBenchmark_Denis_lowerDen_1048PPC_128cells_noSmoothing_sinCenter, '1048 PPC')
plotAvePhi(NGP_RFBenchmark_Denis_lowerDen_2096PPC_128cells_noSmoothing_sinCenter, '2096 PPC')
plotAvePhi(NGP_RFBenchmark_Denis_lowerDen_4192PPC_128cells_noSmoothing_sinCenter, '4192 PPC')
plt.xlim(Exp_RFBenchmark_Denis_moreCells_lowerDen.grid[0], Exp_RFBenchmark_Denis_moreCells_lowerDen.grid[-1]*1e2/2)
plt.ylim(220, 264)
plt.xlabel('Distance (cm)', fontsize = 14)
plt.ylabel(r'Electric Potential (V)', fontsize = 14)
plt.xticks(fontsize=12)
plt.yticks(fontsize=12)
plt.legend(loc = 'lower right', fontsize = 12)
plt.tight_layout()
plt.savefig('Denis_RF/NGP_lowPress_128cells_noneven_phi.pdf')
plt.savefig('Denis_RF/NGP_lowPress_128cells_noneven_phi.png')
plt.close()

plt.figure()
plotAveEPF(Exp_RFBenchmark_Denis_moreCells_lowerDen_20xPart, 'e', label = '2620 PPC Expl.')
plotAveEPF(NGP_RFBenchmark_Denis_lowerDen_524PPC_128cells_noSmoothing_sinCenter, 'e', label= '524 PPC')
plotAveEPF(NGP_RFBenchmark_Denis_lowerDen_1048PPC_128cells_noSmoothing_sinCenter, 'e', label = '1048 PPC')
plotAveEPF(NGP_RFBenchmark_Denis_lowerDen_2096PPC_128cells_noSmoothing_sinCenter, 'e', label =  '2096 PPC')
plotAveEPF(NGP_RFBenchmark_Denis_lowerDen_4192PPC_128cells_noSmoothing_sinCenter, 'e', label = '4192 PPC')
plt.xlabel('Electron Energy (eV)', fontsize = 14)
plt.ylabel(r'Electron PDF (eV$^-{3/2}$)', fontsize = 14)
plt.xticks(fontsize=12)
plt.yticks(fontsize=12)
plt.yscale('linear')
plt.xscale('log')
plt.legend(loc = 'upper right', fontsize = 12)
plt.tight_layout()
plt.savefig('Denis_RF/NGP_lowPress_128cells_noneven_EPF.pdf')
plt.savefig('Denis_RF/NGP_lowPress_128cells_noneven_EPF.png')
plt.close()

plt.figure()
plotAveDensity(NGP_RFBenchmark_Denis_lowerDen_524PPC_128cells_noSmoothing_sinCenter, 'He+', 'Map #1')
plotAveDensity(NGP_RFBenchmark_Denis_lowerDen_524PPC_128cells_noSmoothing_sinCenter_OGTime, 'He+', r'Map #1, Expl. $\Delta t$')
plotAveDensity(NGP_RFBenchmark_Denis_lowerDen_524PPC_128cells_noSmoothing_sinCenter_Curv, 'He+', 'Map #1, analytical')
plotAveDensity(NGP_RFBenchmark_Denis_lowerDen_524PPC_128cells_noSmoothing_sinCenter_5mmEven, 'He+', 'Map #3')
plt.xlim(Exp_RFBenchmark_Denis_moreCells_lowerDen.grid[0], Exp_RFBenchmark_Denis_moreCells_lowerDen.grid[-1]*1e2/2)
plt.ylim(0, None)
plt.xlabel('Distance (cm)', fontsize = 14)
plt.ylabel(r'He$^+$ Density (m$^{-3}$)', fontsize = 14)
plt.xticks(fontsize=12)
plt.yticks(fontsize=12)
plt.legend(loc = 'lower right', fontsize = 12)
plt.tight_layout()
plt.savefig('Denis_RF/NGP_lowPress_128cells_noneven_comp.pdf')
plt.savefig('Denis_RF/NGP_lowPress_128cells_noneven_comp.png')
plt.close()

plt.figure()
xi = np.arange(0, NGP_RFBenchmark_Denis_lowerDen_524PPC_128cells_noSmoothing_sinCenter.Nx-1) + 1
plt.plot(xi, np.diff(NGP_RFBenchmark_Denis_lowerDen_524PPC_128cells_noSmoothing_sinCenter.grid) * 1e3, 'o', label = 'Map #1')
plt.plot(xi, np.diff(NGP_RFBenchmark_Denis_lowerDen_524PPC_128cells_noSmoothing_sinCenter_5mmEven.grid) * 1e3, 'o', label = 'Map #3')
plt.xlim(xi[0], xi[-1])
plt.xlabel(r'Cell Number', fontsize = 14)
plt.ylabel(r'Cell Size (mm)', fontsize = 14)
plt.xticks(fontsize=12)
plt.yticks(fontsize=12)
plt.legend(loc = 'best', fontsize = 12)
plt.tight_layout()
plt.savefig('Denis_RF/lowPress_maps_appendix.pdf')
plt.savefig('Denis_RF/lowPress_maps_appendix.png')
plt.close()



plt.figure()
plotAveDensity(Exp_RFBenchmark_Denis_moreCells_lowerDen_20xPart, 'He+', '2620 PPC Expl.')
plotAveDensity(Exp_RFBenchmark_Denis_lowerDen_doubleTime_1024Cells_64PPC, 'He+', 'Expl, 64 PPC, 1024 cells')
plotAveDensity(CIC_RFBenchmark_Denis_lowerDen_131PPC_64cells_noSmoothing_sinCenter, 'He+', 'ICIC, 131 PPC, 64 cells')
plt.xlim(Exp_RFBenchmark_Denis_moreCells_lowerDen.grid[0], Exp_RFBenchmark_Denis_moreCells_lowerDen.grid[-1]*1e2/2)
plt.ylim(0, None)
plt.xlabel('Distance (cm)', fontsize = 14)
plt.ylabel(r'He$^+$ Density (m$^{-3}$)', fontsize = 14)
plt.xticks(fontsize=12)
plt.yticks(fontsize=12)
plt.legend(loc = 'lower right', fontsize = 12)
plt.tight_layout()
plt.savefig('Denis_RF/CIC_lowRes_comp.pdf')
plt.savefig('Denis_RF/CIC_lowRes_comp.png')
plt.close()

plt.figure()
plotAveDensity(NGP_RFBenchmark_Denis_lowerDen_2000PPC_2500cells_noSmoothing_smallTime, 'He+', '2000 PPC, 2500 Cells')
plotAveDensity(NGP_RFBenchmark_Denis_lowerDen_524PPC_128cells_noSmoothing_denisMap, 'He+', '524 PPC')
plotAveDensity(NGP_RFBenchmark_Denis_lowerDen_1048PPC_128cells_noSmoothing_denisMap, 'He+', '1048 PPC')
plotAveDensity(NGP_RFBenchmark_Denis_lowerDen_2096PPC_128cells_noSmoothing_denisMap, 'He+', '2096 PPC')
plotAveDensity(NGP_RFBenchmark_Denis_lowerDen_4192PPC_128cells_noSmoothing_denisMap, 'He+', '4192 PPC')
plt.xlim(Exp_RFBenchmark_Denis_moreCells_lowerDen.grid[0], Exp_RFBenchmark_Denis_moreCells_lowerDen.grid[-1]*1e2/2)
plt.ylim(0, None)
plt.xlabel('Distance (cm)', fontsize = 14)
plt.ylabel(r'He$^+$ Density (m$^{-3}$)', fontsize = 14)
plt.xticks(fontsize=12)
plt.yticks(fontsize=12)
plt.legend(loc = 'lower right', fontsize = 12)
plt.tight_layout()
plt.savefig('Denis_RF/NGP_lowPress_128cells_DenisMap.pdf')
plt.savefig('Denis_RF/NGP_lowPress_128cells_DenisMap.png')
plt.close()

plt.figure(figsize=(8.0139, 6.2739))
plotAveDensity(NGP_RFBenchmark_Denis_lowerDen_2000PPC_2500cells_noSmoothing_smallTime, 'He+', '2000 PPC, 2500 Cells')
plotAveDensity(NGP_RFBenchmark_Denis_lowerDen_524PPC_128cells_noSmoothing_denisMap, 'He+', '524 PPC')
plotAveDensity(NGP_RFBenchmark_Denis_lowerDen_1048PPC_128cells_noSmoothing_denisMap, 'He+', '1048 PPC')
plotAveDensity(NGP_RFBenchmark_Denis_lowerDen_2096PPC_128cells_noSmoothing_denisMap, 'He+', '2096 PPC')
plotAveDensity(NGP_RFBenchmark_Denis_lowerDen_4192PPC_128cells_noSmoothing_denisMap, 'He+', '4192 PPC')
plt.xlim(Exp_RFBenchmark_Denis_moreCells_lowerDen.grid[0], Exp_RFBenchmark_Denis_moreCells_lowerDen.grid[-1]*1e2/2)
plt.ylim(0, None)
plt.xlabel('Distance (cm)', fontsize = 14)
plt.ylabel(r'He$^+$ Density (m$^{-3}$)', fontsize = 14)
plt.xticks(fontsize=12)
plt.yticks(fontsize=12)
plt.legend(loc = 'lower right', fontsize = 12)
plt.tight_layout()
plt.savefig('Denis_RF/NGP_lowPress_128cells_DenisMap.tif')
plt.close()

plt.figure()
plotAvePhi(NGP_RFBenchmark_Denis_lowerDen_2000PPC_2500cells_noSmoothing_smallTime, '2000 PPC, 2500 Cells')
plotAvePhi(NGP_RFBenchmark_Denis_lowerDen_524PPC_128cells_noSmoothing_denisMap, '524 PPC')
plotAvePhi(NGP_RFBenchmark_Denis_lowerDen_1048PPC_128cells_noSmoothing_denisMap,'1048 PPC')
plotAvePhi(NGP_RFBenchmark_Denis_lowerDen_2096PPC_128cells_noSmoothing_denisMap, '2096 PPC')
plotAvePhi(NGP_RFBenchmark_Denis_lowerDen_4192PPC_128cells_noSmoothing_denisMap, '4192 PPC')
plt.xlim(Exp_RFBenchmark_Denis_moreCells_lowerDen.grid[0], Exp_RFBenchmark_Denis_moreCells_lowerDen.grid[-1]*1e2/2)
plt.ylim(220, 264)
plt.xlabel('Distance (cm)', fontsize = 14)
plt.ylabel(r'Electric Potential', fontsize = 14)
plt.xticks(fontsize=12)
plt.yticks(fontsize=12)
plt.legend(loc = 'lower right', fontsize = 12)
plt.tight_layout()
plt.savefig('Denis_RF/NGP_lowPress_128cells_DenisMap_phi.pdf')
plt.savefig('Denis_RF/NGP_lowPress_128cells_DenisMap_phi.png')
plt.close()

plt.figure()
plt.plot(Powis_32ref[:,0] * 1e2, Powis_32ref[:,1], 'o-', label = 'Powis EC-PIC', markersize = 2)
plotAveDensity(NGP_Powis_benchmark_32ref_test, 'He+', 'INGP')
plt.xlim(NGP_Powis_benchmark_32ref_test.grid[0], NGP_Powis_benchmark_32ref_test.grid[-1]*1e2)
plt.ylim(0, None)
plt.xlabel('Distance (cm)', fontsize = 14)
plt.ylabel(r'He$^+$ Density (m$^{-3}$)', fontsize = 14)
plt.xticks(fontsize=12)
plt.yticks(fontsize=12)
plt.legend(loc = 'lower center', fontsize = 12)
plt.tight_layout()
plt.savefig('Denis_RF/Powis_comp.pdf')
plt.savefig('Denis_RF/Powis_comp.png')
plt.close()

plt.figure()
xi = np.arange(0, NGP_RFBenchmark_Denis_lowerDen_524PPC_128cells_noSmoothing_denisMap.Nx-1) + 1
plt.plot(xi, np.diff(NGP_RFBenchmark_Denis_lowerDen_524PPC_128cells_noSmoothing_sinCenter.grid)*1e2, 'o', label = 'Map #1')
plt.plot(xi, np.diff(NGP_RFBenchmark_Denis_lowerDen_524PPC_128cells_noSmoothing_denisMap.grid)*1e2, 'o', label = 'Map #2')
plt.xlim(xi[0], xi[-1])
plt.xlabel(r'Cell Number', fontsize = 14)
plt.ylabel(r'Cell Size (cm)', fontsize = 14)
plt.xticks(fontsize=12)
plt.yticks(fontsize=12)
plt.legend(loc = 'best', fontsize = 12)
plt.tight_layout()
plt.savefig('Denis_RF/lowPress_maps.pdf')
plt.savefig('Denis_RF/lowPress_maps.png')
plt.close()

plt.figure()
density_std_plots(NGP_RFBenchmark_Denis_lowerDen_524PPC_128cells_noSmoothing_sinCenter_try, 'e', 2000, label = 'Map #1 Low Press.')
density_std_plots(NGP_RFBenchmark_Denis_lowerDen_524PPC_128cells_noSmoothing_denisMap_try, 'e', 2000, label = 'Map #2 Low Press.')
density_std_plots(NGP_RFBenchmark_Denis_524PPC_128cells_noSmoothing_sinCenter, 'e', 2000, label = 'Map #1 High Press.')
density_std_plots(NGP_RFBenchmark_Denis_lowerDen_262PPC_256cells_noSmoothing, 'e', 2000, label = 'Uniform 256 Cells Low Press.')
plt.xlim(Exp_RFBenchmark_Denis_moreCells_lowerDen.grid[0], Exp_RFBenchmark_Denis_moreCells_lowerDen.grid[-1]*1e2)
plt.ylim(0, None)
plt.xlabel('Distance (cm)', fontsize = 14)
plt.ylabel(r'Std. dev. $n_e$ (m$^{-3}$)', fontsize = 14)
plt.xticks(fontsize=12)
plt.yticks(fontsize=12)
plt.legend(loc = 'upper right', fontsize = 12)
plt.tight_layout()
plt.savefig('Denis_RF/std_dev_e_density.pdf')
plt.savefig('Denis_RF/std_dev_e_density.png')
plt.close()

plt.figure()
Efield_std_plots(NGP_RFBenchmark_Denis_lowerDen_524PPC_128cells_noSmoothing_sinCenter_try, 2000, label = 'Map #1 Low Press.')
Efield_std_plots(NGP_RFBenchmark_Denis_lowerDen_524PPC_128cells_noSmoothing_denisMap_try, 2000, label = 'Map #2 Low Press.')
Efield_std_plots(NGP_RFBenchmark_Denis_524PPC_128cells_noSmoothing_sinCenter, 2000, label = 'Map #1 High Press.')
Efield_std_plots(NGP_RFBenchmark_Denis_lowerDen_262PPC_256cells_noSmoothing, 2000, label = 'Uniform 256 Cells Low Press.')
plt.xlim(Exp_RFBenchmark_Denis_moreCells_lowerDen.grid[0], Exp_RFBenchmark_Denis_moreCells_lowerDen.grid[-1]*1e2)
plt.ylim(0, 15000)
plt.xlabel('Distance (cm)', fontsize = 14)
plt.ylabel(r'Std. dev. E-field (V/m)', fontsize = 14)
plt.xticks(fontsize=12)
plt.yticks(fontsize=12)
plt.legend(loc = 'upper right', fontsize = 12)
plt.tight_layout()
plt.savefig('Denis_RF/std_dev_EField.pdf')
plt.savefig('Denis_RF/std_dev_EField.png')
plt.close()
